/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoPI3.Inteface_principal;

import java.awt.CardLayout;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author NadsonJR
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Empty = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelCadastrarProduto1 = new ProjetoPI3.Inteface_Produto.PainelCadastrarProduto();
        painelConsultarProduto1 = new ProjetoPI3.Inteface_Produto.PainelConsultarProduto();
        painelCategoria1 = new ProjetoPI3.Inteface_Produto.PainelCategoria();
        painelCadastroCliente1 = new ProjetoPI3.Interface_Cliente.painelCadastroCliente();
        jMenuBar1 = new javax.swing.JMenuBar();
        BarraProduto = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        CategoriaMenu = new javax.swing.JMenuItem();
        BarraClient = new javax.swing.JMenu();
        CadastrarCliente = new javax.swing.JMenuItem();
        ConsultarCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gif Redimensionado2.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(469, 602));
        jLabel1.setMinimumSize(new java.awt.Dimension(469, 602));
        jLabel1.setPreferredSize(new java.awt.Dimension(469, 602));

        javax.swing.GroupLayout EmptyLayout = new javax.swing.GroupLayout(Empty);
        Empty.setLayout(EmptyLayout);
        EmptyLayout.setHorizontalGroup(
            EmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        EmptyLayout.setVerticalGroup(
            EmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 469, Short.MAX_VALUE)
        );

        MainPanel.add(Empty, "empty");
        MainPanel.add(painelCadastrarProduto1, "TelaDeCadastro");
        MainPanel.add(painelConsultarProduto1, "TelaDeAlteracao");
        MainPanel.add(painelCategoria1, "CategoriaEdicao");
        MainPanel.add(painelCadastroCliente1, "CadastrarCliente");

        jMenuBar1.setBackground(new java.awt.Color(161, 255, 255));

        BarraProduto.setText("Produto");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        BarraProduto.add(jMenuItem1);

        jMenuItem2.setText("Consultar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        BarraProduto.add(jMenuItem2);

        CategoriaMenu.setText("Categoria");
        CategoriaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaMenuActionPerformed(evt);
            }
        });
        BarraProduto.add(CategoriaMenu);

        jMenuBar1.add(BarraProduto);

        BarraClient.setText("Cliente");

        CadastrarCliente.setText("Cadastrar");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        BarraClient.add(CadastrarCliente);

        ConsultarCliente.setText("Consultar");
        BarraClient.add(ConsultarCliente);

        jMenuBar1.add(BarraClient);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout Card = (CardLayout) MainPanel.getLayout();
        Card.show(MainPanel, "TelaDeCadastro");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout Card = (CardLayout) MainPanel.getLayout();
        Card.show(MainPanel, "TelaDeAlteracao");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        painelCadastrarProduto1.getCancelar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CardLayout card = (CardLayout) MainPanel.getLayout();
                card.show(MainPanel, "empty");
            }
        });

        painelConsultarProduto1.getCancelar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CardLayout card = (CardLayout) MainPanel.getLayout();
                card.show(MainPanel, "empty");
            }
            
        });
        painelCategoria1.getCancelar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CardLayout card = (CardLayout) MainPanel.getLayout();
                card.show(MainPanel, "empty");
            }
        });
        painelCadastroCliente1.getCancelar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CardLayout card = (CardLayout) MainPanel.getLayout();
                card.show(MainPanel, "empty");
            }
        });
    }//GEN-LAST:event_formWindowOpened

    private void CategoriaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaMenuActionPerformed
        CardLayout Card = (CardLayout) MainPanel.getLayout();
        Card.show(MainPanel, "CategoriaEdicao");
    }//GEN-LAST:event_CategoriaMenuActionPerformed

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
         CardLayout Card = (CardLayout) MainPanel.getLayout();
        Card.show(MainPanel, "CadastrarCliente");   // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BarraClient;
    private javax.swing.JMenu BarraProduto;
    private javax.swing.JMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CategoriaMenu;
    private javax.swing.JMenuItem ConsultarCliente;
    private javax.swing.JPanel Empty;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private ProjetoPI3.Inteface_Produto.PainelCadastrarProduto painelCadastrarProduto1;
    private ProjetoPI3.Interface_Cliente.painelCadastroCliente painelCadastroCliente1;
    private ProjetoPI3.Inteface_Produto.PainelCategoria painelCategoria1;
    private ProjetoPI3.Inteface_Produto.PainelConsultarProduto painelConsultarProduto1;
    // End of variables declaration//GEN-END:variables
}
